# Generated by Django 4.2.6 on 2023-10-27 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_layers', '0002_remove_campaignlayer_doi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doi',
            old_name='doi_url',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='doi',
            name='campaign_layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dois', to='campaign_layers.campaignlayer'),
        ),
        migrations.AlterField(
            model_name='instrumentlayer',
            name='campaign_layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrumentlayers', to='campaign_layers.campaignlayer'),
        ),
        migrations.AlterField(
            model_name='legend',
            name='campaign_layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legends', to='campaign_layers.campaignlayer'),
        ),
        migrations.AlterField(
            model_name='link',
            name='campaign_layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='campaign_layers.campaignlayer'),
        ),
    ]
