# Generated by Django 4.2.6 on 2023-10-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_layers', '0004_alter_campaignlayer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlayer',
            name='name',
            field=models.CharField(default='HS3', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentlayer',
            name='field_campagin_name',
            field=models.CharField(default='HS3', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentlayer',
            name='variable_name',
            field=models.CharField(default='zku (ka/ku Radar Reflectivity)', max_length=500),
            preserve_default=False,
        ),
    ]
