# Generated by Django 4.2.6 on 2023-10-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_layers', '0006_alter_instrumentlayer_variable_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrumentlayer',
            old_name='field_campagin_name',
            new_name='field_campaign_name',
        ),
    ]
