# Use postgres/example user/password credentials
version: '3.1'

services:
  pgsqldb:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8009:8080
    depends_on:
      - pgsqldb
  
  api:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret123
    depends_on:
      - pgsqldb