# Generated by Django 4.2.6 on 2023-10-26 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=100)),
                ('instrument_short_name', models.CharField(max_length=100)),
                ('doi_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('instrument_short_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('display_mechanism', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('add_tick_event_listner', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_short_name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('logo_url', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('doi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_layers', to='campaign_layers.doi')),
                ('instrument_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_layers', to='campaign_layers.instrumentlayer')),
                ('legend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_layers', to='campaign_layers.legend')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_layers', to='campaign_layers.link')),
            ],
        ),
    ]
