# Generated by Django 4.2.6 on 2023-10-26 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_layers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignlayer',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='campaignlayer',
            name='instrument_layer',
        ),
        migrations.RemoveField(
            model_name='campaignlayer',
            name='legend',
        ),
        migrations.RemoveField(
            model_name='campaignlayer',
            name='link',
        ),
        migrations.AddField(
            model_name='doi',
            name='campaign_layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign_layers.campaignlayer'),
        ),
        migrations.AddField(
            model_name='instrumentlayer',
            name='campaign_layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign_layers.campaignlayer'),
        ),
        migrations.AddField(
            model_name='legend',
            name='campaign_layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign_layers.campaignlayer'),
        ),
        migrations.AddField(
            model_name='link',
            name='campaign_layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign_layers.campaignlayer'),
        ),
    ]
